name: Deploy Angular app to GitHub Pages

on:
  push:
    branches:
      - main  # falls dein Hauptbranch main heißt

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: ng build --prod --base-href "https://olusprogr.github.io/angular-typescript-backend-mongodb-tutorial/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/angular-typescript-backend-mongodb-tutorial
